APPLICATION = saul
include ../Makefile.tests_common

# include and auto-initialize all available sensors
USEMODULE += saul_reg
USEMODULE += saul_poll
USEMODULE += saul_default
USEMODULE += auto_init_saul

include $(RIOTBASE)/Makefile.include
