# RIOT specific dependencies
USEMODULE += posix_semaphore
USEMODULE += event_callback
USEMODULE += xtimer

# glue code
USEMODULE += nimble_riot_contrib

# RIOT port
USEMODULE += nimble_porting_nimble
USEMODULE += nimble_npl_riot

# if nothing else is specified, we build the host and controller
ifeq (,$(filter nimble_host nimble_controller,$(USEMODULE)))
  USEMODULE += nimble_host
  USEMODULE += nimble_controller
endif

# include host dependencies
ifneq (,$(filter nimble_host,$(USEMODULE)))
  USEMODULE += nimble_host_util
  USEMODULE += nimble_tinycrypt
  USEMODULE += nimble_host_store_ram
endif

# nimble controller dependencies
ifneq (,$(filter nimble_controller,$(USEMODULE)))
  USEMODULE += nimble_transport_ram
  ifeq (nrf52,$(CPU_FAM))
    USEMODULE += nimble_drivers_nrf52
  endif
endif

# RIOT specific submodule dependencies
ifneq (,$(filter nimble_addr,$(USEMODULE)))
  USEMODULE += bluetil_addr
endif

ifneq (,$(filter nimble_scanlist,$(USEMODULE)))
  USEMODULE += nimble_addr
  USEMODULE += bluetil_ad
endif

ifneq (,$(filter nimble_netif,$(USEMODULE)))
  USEMODULE += l2util
endif

ifneq (,$(filter nimble_netif_autoconn_%,$(USEMODULE)))
  USEMODULE += nimble_netif_autoconn
  USEMODULE += nimble_netif
endif

ifneq (,$(filter nimble_netif_rpble,$(USEMODULE)))
  USEMODULE += gnrc_rpl
  USEMODULE += nimble_netif
  USEMODULE += nimble_scanner
  USEMODULE += bluetil_ad
  USEMODULE += bluetil_addr
  USEMODULE += event_timeout
endif
