APPLICATION = driver_sdcard_spi
include ../Makefile.tests_common

FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_spi

USEMODULE += sdcard_spi
USEMODULE += fmt
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
