APPLICATION = driver_spfd5408
include ../Makefile.tests_common

# exclude boards with insufficient memory
BOARD_INSUFFICIENT_MEMORY :=

USEMODULE += spfd5408
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
